# -*- coding: utf-8 -*-
"""Python_03_.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fv0CZ6UMWwEsuxUx5wn-WsJsZAr97MDY

# Python para Data Science

##01.Variáveis
"""

#descobrindo o tipo de uma variável

quantidade = 4
type(quantidade)

"""##02.Métodos

"""

#métodos: funções que estão associadas a objetos, e a partir delas são realizadas ações e operações

#Manipulando strings
texto = " Juliana Lopes Suza "

texto = texto.strip().replace('Suza', 'Souza').upper()

print(texto)

#Métodos para listas

raca_caes = ['Labrador Retriever',
             'Bulldog Francês',
             'Pastor Alemão',
             'Poodle']

#insere um elemento em determinada posição
raca_caes.insert(1, 'Golden Retriever')
raca_caes

#mostra a posição de um elemento
raca_caes.index('Pastor Alemão')

#organiza em ordem crescente
raca_caes.sort()
raca_caes

"""##03.Coletando e manipulando dados

"""

nota = float(input('Digite a nota do aluno: '))
print(f'A nota do aluno é {nota}')

print('Quantidade\tQualidade\n5 amostras\tAlta\n3 amostras\tBaixa')

"""## 04.Contador com while"""

contador = 1
while contador <=10:
  print(contador)
  contador += 1

"""##05.Construindo listas

"""

lista = ['Juliana lopes', 9.5,9.0,8.0, True]

#retornando um resultado a partir do índice
lista [1]

#iterando a lista:
for elemento in lista:
  print(elemento)

#atualizando um item da lista
lista [3] = 10.0
lista

#manipulando listas
len(lista)

#adicionando elemento ao final da lista
lista.append(9.7)

#removendo elementos da lista
lista.remove(9.7)

lista

"""##06.Usando dicionários"""

loja = {'nomes': ['televisão', 'celular', 'notebook', 'geladeira', 'fogão'],
        'precos': [2000, 1500, 3500, 4000, 1500]}

for chave, elementos in loja.items():
  print(f'Chave: {chave}\nElementos:')
  for dado in elementos:
    print(dado)