# -*- coding: utf-8 -*-
"""Python_05_trabalhando_com_bibliotecas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1deYUCr7eqAQdZ_Dzj8mnZwGJl5hd-9Xi
"""

#Mostrando todos os pacotes já instalados e suas versões
!pip list

#Instalando uma biblioteca matplotlib pelo pip
!pip install matplotlib

#Instalando uma versão específica
#!pip install matplotlib==3.6.2

#Importando a biblioteca sem alias
import matplotlib

#Testando a importação
matplotlib.__version__

#01 - Testando a matplotlib em um exemplo de média de estudantes

#Importanto uma bilioteca com alias
import matplotlib.pyplot as plt

plt.show

estudantes = ["João", "Maria", "José"]
notas = [8.5,9,6.5]
#Importante rodar antes de criar o gráfico

#Criando um gráfico de barras, com parâmetros ()
plt.bar(x = estudantes, height = notas)

#02 - Usando a biblioteca Random

estudantes_2 = ["João", "Maria", "José", "Ana"]

# Importando uma função específica de uma biblioteca
from random import choice

#Retorna ua descrição sobre a variável, método ou classe
help(choice)

#Usando o método, colocando dentro da variável e imprimindo
estudante = choice(estudantes_2)
print(estudante)